const projects = [ {
    title: 'MER Review Agent — Production AI Agent',
    description: 'A production AI agent that automates month-end balance-sheet reviews for a 270+-client accounting firm. Combines a tool-calling LLM agent, a deterministic 34-rule validation engine, and a multi-extractor document pipeline (Azure Document Intelligence + LLM/vision) to cut per-client review from hours to minutes. Built solo during my Optimus co-op.',
    technologies: ["Python", "FastAPI", "Pydantic", "Azure OpenAI", "Microsoft Agent Framework", "Vision-Language Models", "Azure Document Intelligence", "Azure Container Apps", "Azure Container Registry", "Docker", "Cosmos DB", "Azure Blob Storage", "Azure Key Vault", "Microsoft Entra ID", "Azure Application Insights", "OpenTelemetry", "pytest", "React", "TypeScript"],
    category: "Professional",
    github: '',
    caseStudy: '/work/mer-agent',
  }, {
    title: 'cafe-manager — Canadian Payroll Engine',
    description: 'A CRA-compliant payroll engine in Java that computes CPP, EI, and federal/BC income tax with BigDecimal precision — validated to the cent against the CRA PDOC reference across 8 pay periods and 7 deduction types. Built to replace a ~$200/mo payroll service for a local cafe.',
    technologies: ["Java", "Gradle", "SQLite", "JUnit"],
    category: "Personal",
    github: 'https://github.com/rayzelltj/cafe-manager',
    devpost: '',
  }, {
    title: 'BrainJack! (nwHacks 2025)',
    description: 'A web application that combines the excitement of blackjack with educational quizzes, allowing players to reinforce study material through strategic risk and reward.',
    technologies: [ "JavaScript", "HTML/CSS", "MongoDB"],
    category: "Hackathon",
    github: 'https://github.com/mliu000/nwhacks-2025-BrainJack',
    devpost: 'https://devpost.com/software/brainjack',
    image: '/images/brainjack.png',
  }, {
    title: 'MedLex (HackCamp 2024)',
    description: 'A web application that converts user-reported symptoms into precise medical terminology, providing a clearer understanding of potential health conditions.',
    technologies: ["React", "Node.js", "Figma", "C++", "JavaScript", "HTML/CSS"],
    category: "Hackathon",
    github: 'https://github.com/rayzelltj/HackCamp2024_MedLex',
    devpost: 'https://devpost.com/software/medlex',
    image: '/images/medlex.png',
  }, {
    title: 'Online Coffee Order Manager (CPSC 210)',
    description: 'A desktop application that streamlines online coffee ordering by enabling customers to manage orders, view sales history, and store customer data through a user-friendly Swing-based interface.',
    technologies: ["Java"],
    category: "Course Project",
    github: 'https://github.com/rayzelltj/online-ordering-software-project',
    devpost: '',
    image: '/images/cpsc210.png',
  }, {
    title: 'Pulsar Star Classification Model (DSCI 100)',
    description: 'A machine learning model utilizing K-NN classification to accurately identify pulsar stars with 97.6% precision using the HTRU2 dataset.',
    technologies: ["Python", "pandas", "scikit-learn", "NumPy", "Matplotlib", "Altair"],
    category: "Course Project",
    github: 'https://github.com/rayzelltj/data-science-project',
    devpost: '',
    image: '/images/dsci100project.png',
  },
];

export default projects;